# frozen_string_literal: true

source 'https://rubygems.org'

source 'https://rubygems.org'

gem 'erubis'
gem 'pry'
gem 'rackup'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'tilt'
gem 'webrick'

ruby '3.2.2'
