require 'yaml'
require_relative 'extract_data'

desc 'add_handlers'
task :add do
  recent_user = extract_data.first.last
  file_name = recent_user.split('-').map(&:downcase).join
  file = File.new('user_interest_app.rb', 'a+')
  
  File.open("views/users.erb", 'w+') do |user_layout|
    erb_file = File.new("views/users/#{file_name}.erb", 'w+')
    erb_file.write(user_layout.read) 
  end
  file.puts(
    "\nget \"/#{recent_user}\" do\n"\
    "\terb :#{file_name}\n"\
    "end\n"
  )
  file.close
end
