# frozen_string_literal: true

source "https://rubygems.org"

gem 'erubi'
gem 'sinatra'
gem 'sinatra-contrib'

ruby '3.2.0'

group :production do
  gem 'puma'
end

gem "rackup", "~> 2.2"

gem "pry", "~> 0.15.2"

gem "rack-test", "~> 2.2"

gem "minitest", "~> 5.25"

gem "redcarpet", "~> 3.6"

gem "pry-byebug", "~> 3.8"
gem "minitest-reporters"